[package]
name = "callysto"
version = "0.1.0"
authors = ["Theo Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bastion = { git = "https://github.com/bastion-rs/bastion.git" }
lightproc = "0.3.5"
#lever = "0.1"
lever = { path = "../lever" }
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
futures-timer = "3.0"
rdkafka = { version = "0.26", default-features = false, features = ["libz"]}
tracing = "0.1"
